
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED'
export const LOGIN_FAIL= 'LOGIN_FAIL'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCEED = 'REGISTER_SUCCEED'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const BUY_SHARE_REQUEST = 'BUY_SHARE_REQUEST'
export const BUY_SHARE_SUCCEED = 'BUY_SHARE_SUCCEED'
export const BUY_SHARE_FAIL = 'BUY_SHARE_FAIL'

export const TOKEN_RECEIVE = 'TOKEN_RECEIVE'
export const TOKEN_VERIFY = 'TOKEN_VERIFY'
export const TOKEN_REJECT = 'TOKEN_REJECT'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCEED = 'LOGOUT_SUCCEED'